// <auto-generated />
namespace TodoList.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingpasswordtouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingpasswordtouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201708261647027_Adding-password-to-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
